import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/navbar";
import { cn } from "@/lib/utils";
import ReduxProvider from "@/providers/redux-provider";
import ModalProvider from "@/providers/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Drf Nextjs Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("", inter.className)}>
        <ReduxProvider>
          <ModalProvider />
          <Navbar />
          <div className="pt-32">{children}</div>
        </ReduxProvider>
      </body>
    </html>
  );
}
