services:
  redis:
    image: redis:7.4.0-alpine

  django:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=drf_nextjs_airbnb

  celery:
    build: ./backend
    command: ["celery", "-A", "backend", "worker", "--loglevel=info"]
    volumes:
      - ./backend:/backend
    env_file:
      - .env.dev
    depends_on:
      - redis

  celery-beat:
    build: ./backend
    command: ["celery", "-A", "backend", "beat", "--loglevel=info"]
    volumes:
      - ./backend:/backend
    env_file:
      - .env.dev
    depends_on:
      - redis

volumes:
  postgres_data:
