services:
  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    command: redis-server --port 6380
    profiles: [celery]

  django:
    build: ./backend
    container_name: django
    volumes:
      - django:/usr/src/django/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - database

  database:
    image: postgres:16.3-alpine
    container_name: database
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - "1234:1234"
    command: -p 1234

  celery:
    build: ./backend
    container_name: celery
    profiles: [celery]
    command: ["celery", "-A", "backend", "worker", "--loglevel=info"]
    volumes:
      - django:/usr/src/django/
    env_file:
      - .env.dev
    depends_on:
      - redis

  celery-beat:
    build: ./backend
    container_name: celery-beat
    profiles: [celery]
    command: ["celery", "-A", "backend", "beat", "--loglevel=info"]
    volumes:
      - django:/usr/src/django/
    env_file:
      - .env.dev
    depends_on:
      - redis

  nextjs:
    build: ./frontend
    container_name: nextjs
    volumes:
      - nextjs:/usr/src/nextjs/
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    profiles: [nextjs]

volumes:
  postgres:
  nextjs:
  django: