services:
  redis:
    image: redis:7.4.0-alpine
    command: redis-server --port 6380

  django:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - database
      - redis

  database:
    image: postgres:16.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - "1234:1234"
    command: -p 1234

  celery:
    build: ./backend
    command: ["celery", "-A", "backend", "worker", "--loglevel=info"]
    volumes:
      - ./backend:/backend
    env_file:
      - .env.dev
    depends_on:
      - redis

  celery-beat:
    build: ./backend
    command: ["celery", "-A", "backend", "beat", "--loglevel=info"]
    volumes:
      - ./backend:/backend
    env_file:
      - .env.dev
    depends_on:
      - redis

volumes:
  postgres:
